#!/bin/bash


############################ SERVICE VARIABLES ############################
# Run Notebook as this user ID and group ID
USER=stratio
GROUP=stratio

# Define other required variables
RUN_DIR="/var/run/sds"
PIDFILE="$RUN_DIR/$NAME.pid"
LOCKFILE="/var/lock/subsys/$NAME"
LOGFILE="/var/log/sds/notebook/notebook.log"
DAEMON="/opt/sds/notebook/bin/notebook"
DAEMON_OPTS=" -l $LOGFILE -p $PIDFILE"

